basePath: /
definitions:
  errors.Error:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  schemas.Communities:
    properties:
      communities:
        items:
          $ref: '#/definitions/schemas.Community'
        type: array
    type: object
  schemas.Community:
    properties:
      id:
        type: string
      image_url:
        type: string
      name:
        type: string
      number_subscriptions:
        type: integer
      purpose:
        type: string
    type: object
  schemas.CreateCommunityRequest:
    properties:
      image_url:
        type: string
      name:
        type: string
      purpose:
        type: string
    type: object
  schemas.CreateProfessionalRequest:
    properties:
      email:
        type: string
      first_last_name:
        type: string
      image_url:
        type: string
      name:
        type: string
      phone_number:
        type: string
      second_last_name:
        type: string
      specialty:
        type: string
      type:
        type: string
    type: object
  schemas.CreateUserRequest:
    properties:
      email:
        type: string
      first_last_name:
        type: string
      image_url:
        type: string
      memberships:
        items:
          $ref: '#/definitions/schemas.Membership'
        type: array
      name:
        type: string
      onboarding:
        $ref: '#/definitions/schemas.Onboarding'
      password:
        type: string
      rol:
        type: string
      second_last_name:
        type: string
    type: object
  schemas.IdentificationDocument:
    properties:
      document_number:
        type: string
      document_type:
        type: string
      id:
        type: string
    type: object
  schemas.Membership:
    properties:
      community:
        $ref: '#/definitions/schemas.Community'
      description:
        type: string
      end_date:
        type: string
      id:
        type: string
      start_date:
        type: string
      status:
        $ref: '#/definitions/schemas.MembershipStatus'
    type: object
  schemas.MembershipStatus:
    enum:
    - ACTIVE
    - EXPIRED
    - CANCELLED
    type: string
    x-enum-varnames:
    - MembershipStatusActive
    - MembershipStatusExpired
    - MembershipStatusCancelled
  schemas.Onboarding:
    properties:
      address:
        type: string
      city:
        type: string
      district:
        type: string
      id:
        type: string
      identification_document:
        $ref: '#/definitions/schemas.IdentificationDocument'
      phone_number:
        type: string
      postal_code:
        type: string
    type: object
  schemas.Professional:
    properties:
      email:
        type: string
      first_last_name:
        type: string
      id:
        type: string
      image_url:
        type: string
      name:
        type: string
      phone_number:
        type: string
      second_last_name:
        type: string
      specialty:
        type: string
      type:
        type: string
    type: object
  schemas.Professionals:
    properties:
      professionals:
        items:
          $ref: '#/definitions/schemas.Professional'
        type: array
    type: object
  schemas.UpdateCommunityRequest:
    properties:
      image_url:
        type: string
      name:
        type: string
      purpose:
        type: string
    type: object
  schemas.UpdateProfessionalRequest:
    properties:
      email:
        type: string
      first_last_name:
        type: string
      image_url:
        type: string
      name:
        type: string
      phone_number:
        type: string
      second_last_name:
        type: string
      specialty:
        type: string
      type:
        type: string
    type: object
  schemas.UpdateUserRequest:
    properties:
      email:
        type: string
      first_last_name:
        type: string
      image_url:
        type: string
      memberships:
        items:
          $ref: '#/definitions/schemas.Membership'
        type: array
      name:
        type: string
      onboarding:
        $ref: '#/definitions/schemas.Onboarding'
      password:
        type: string
      rol:
        type: string
      second_last_name:
        type: string
    type: object
  schemas.User:
    properties:
      email:
        type: string
      first_last_name:
        type: string
      id:
        type: string
      image_url:
        type: string
      memberships:
        items:
          $ref: '#/definitions/schemas.Membership'
        type: array
      name:
        type: string
      onboarding:
        $ref: '#/definitions/schemas.Onboarding'
      password:
        type: string
      rol:
        $ref: '#/definitions/schemas.UserRol'
      second_last_name:
        type: string
    type: object
  schemas.UserRol:
    enum:
    - ADMINISTRATOR
    - CLIENT
    type: string
    x-enum-varnames:
    - UserRolAdmin
    - UserRolClient
  schemas.Users:
    properties:
      users:
        items:
          $ref: '#/definitions/schemas.User'
        type: array
    type: object
info:
  contact: {}
  description: AstroCat API sample for clients
  title: AstroCat API
  version: "1.0"
paths:
  /community/:
    get:
      consumes:
      - application/json
      description: Fetch all communities, filtered by params.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Communities'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Fetch Communities.
      tags:
      - Community
    post:
      consumes:
      - application/json
      description: Create the community information.
      parameters:
      - description: Create Community Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.CreateCommunityRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.Community'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Create Community.
      tags:
      - Community
  /community/{communityId}/:
    get:
      consumes:
      - application/json
      description: Gets a community given its id.
      parameters:
      - description: Community ID
        in: path
        name: communityId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Community'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Get Community.
      tags:
      - Community
    patch:
      consumes:
      - application/json
      description: Update the community information.
      parameters:
      - description: Community ID
        in: path
        name: communityId
        required: true
        type: string
      - description: Update Community Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.UpdateCommunityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/schemas.Community'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Update Community.
      tags:
      - Community
  /health-check/:
    get:
      consumes:
      - application/json
      description: Verify connection in swagger
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health Check
      tags:
      - Health Check
  /professional/:
    get:
      consumes:
      - application/json
      description: Fetch all professionals, filtered by params.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Professionals'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Fetch Professionals.
      tags:
      - Professional
    post:
      consumes:
      - application/json
      description: Creates a new professional.
      parameters:
      - description: Create Professional Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.CreateProfessionalRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.Professional'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Create Professional.
      tags:
      - Professional
  /professional/{professionalId}/:
    get:
      consumes:
      - application/json
      description: Gets a professional given its id.
      parameters:
      - description: Professional ID
        in: path
        name: professionalId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Professional'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Get Professional.
      tags:
      - Professional
    patch:
      consumes:
      - application/json
      description: Updates a professional given its id.
      parameters:
      - description: Professional ID
        in: path
        name: professionalId
        required: true
        type: string
      - description: Update Professional Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.UpdateProfessionalRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Professional'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Update Professional.
      tags:
      - Professional
  /user/:
    get:
      consumes:
      - application/json
      description: Fetch all users, filtered by params.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Fetch Users.
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Creates a new user.
      parameters:
      - description: Create User Request
        in: body
        name: createUserRequest
        required: true
        schema:
          $ref: '#/definitions/schemas.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Create User.
      tags:
      - User
  /user/{userId}/:
    get:
      consumes:
      - application/json
      description: Gets a user given its id.
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Get User.
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Updates a user given its id.
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: Update User Request
        in: body
        name: updateUserRequest
        required: true
        schema:
          $ref: '#/definitions/schemas.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Update User.
      tags:
      - User
swagger: "2.0"
