basePath: /
definitions:
  errors.Error:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  schemas.Communities:
    properties:
      communities:
        items:
          $ref: '#/definitions/schemas.Community'
        type: array
    type: object
  schemas.Community:
    properties:
      id:
        type: string
      image_url:
        type: string
      name:
        type: string
      number_subscriptions:
        type: integer
      purpose:
        type: string
    type: object
  schemas.CreateCommunityRequest:
    properties:
      image_url:
        type: string
      name:
        type: string
      purpose:
        type: string
    type: object
  schemas.CreateServiceRequest:
    properties:
      description:
        type: string
      image_url:
        type: string
      is_virtual:
        type: boolean
      name:
        type: string
    type: object
  schemas.Service:
    properties:
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      is_virtual:
        type: boolean
      name:
        type: string
    type: object
  schemas.Services:
    properties:
      services:
        items:
          $ref: '#/definitions/schemas.Service'
        type: array
    type: object
  schemas.UpdateCommunityRequest:
    properties:
      image_url:
        type: string
      name:
        type: string
      purpose:
        type: string
    type: object
  schemas.UpdateServiceRequest:
    properties:
      description:
        type: string
      image_url:
        type: string
      is_virtual:
        type: boolean
      name:
        type: string
    type: object
info:
  contact: {}
  description: AstroCat API sample for clients
  title: AstroCat API
  version: "1.0"
paths:
  /community/:
    get:
      consumes:
      - application/json
      description: Fetch all communities, filtered by params.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Communities'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Fetch Communities.
      tags:
      - Community
    post:
      consumes:
      - application/json
      description: Create the community information.
      parameters:
      - description: Create Community Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.CreateCommunityRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.Community'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Create Community.
      tags:
      - Community
  /community/{communityId}/:
    get:
      consumes:
      - application/json
      description: Gets a community given its id.
      parameters:
      - description: Community ID
        in: path
        name: communityId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Community'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Get Community.
      tags:
      - Community
    patch:
      consumes:
      - application/json
      description: Update the community information.
      parameters:
      - description: Community ID
        in: path
        name: communityId
        required: true
        type: string
      - description: Update Community Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.UpdateCommunityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/schemas.Community'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Update Community.
      tags:
      - Community
  /health-check/:
    get:
      consumes:
      - application/json
      description: Verify connection in swagger
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health Check
      tags:
      - Health Check
  /service/:
    get:
      consumes:
      - application/json
      description: Fetch all services, filtered by params.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Services'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Fetch Services.
      tags:
      - Service
    post:
      consumes:
      - application/json
      description: Create the service information.
      parameters:
      - description: Create Service Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.CreateServiceRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.Service'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Create Service.
      tags:
      - Service
  /service/{serviceId}/:
    get:
      consumes:
      - application/json
      description: Gets a service given its id.
      parameters:
      - description: Service ID
        in: path
        name: serviceId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Service'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Get Service.
      tags:
      - Service
    patch:
      consumes:
      - application/json
      description: Update the service information.
      parameters:
      - description: Service ID
        in: path
        name: serviceId
        required: true
        type: string
      - description: Update Service Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.UpdateServiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/schemas.Service'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Missing or malformed JWT
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      security:
      - JWT: []
      summary: Update Service.
      tags:
      - Service
swagger: "2.0"
